version: "3.9"

services:
  app:
    container_name: app-container
    
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.app

    ports:
      - "8000:8000"
    
    volumes:
      - ../src/cc_music:/app/cc_music
      - storage_data:/data/files

    env_file:
      - ../.env

    depends_on:
      - storage

  storage:
    container_name: storage-container

    build:
      context: ../
      dockerfile: ./docker/Dockerfile.storage

    ports:
      - "3306:3306"
    
    volumes:
      - mysql_data:/var/lib/mysql

    env_file:
      - ../.env

volumes:
  storage_data:
    name: storage_data
  mysql_data:
    name: mysql_data